name: Publish package to the Maven Central Repository
on:
  pull_request:

jobs:
  publish:
    env:
      BANDWIDTH_URL_WEBRTC_SERVER: ${{ secrets.BANDWIDTH_URL_WEBRTC_SERVER }}
      BANDWIDTH_URL_WEBRTC_CONFERENCE_SERVER: ${{ secrets.BANDWIDTH_URL_WEBRTC_CONFERENCE_SERVER }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Get Gradle project version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: Publish to Apache Maven Central
      run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1
      env:
        OSSRH_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
